import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./_components/Navbar";
import "./globals.css";

const chillax = localFont({
	src: "./fonts/Chillax-Variable.ttf",
});

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${chillax.className} antialiased bg-black`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
